#!/usr/bin/env python
#
# Copyright (C) 2008 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Generates a VFAT EFI System partition image from a provided
zip file containing its contents relative to the root directory
"""

import sys

if sys.hexversion < 0x02040000:
    print >> sys.stderr, "Python 2.4 or newer is required."
    sys.exit(1)

# Android Release Tools
sys.path.append("build/tools/releasetools")
import common

sys.path.append("device/intel/build/releasetools")
import intel_common

OPTIONS = common.OPTIONS

def main(argv):

    def option_handler(o, a):
        if o in ("-i", "--size"):
            OPTIONS.size = int(a)
        elif o in ("-z", "--zipfile"):
            OPTIONS.zipfile = a
        else:
            return False
        return True

    args = common.ParseOptions(argv, __doc__,
                            extra_opts="i:z:",
                            extra_long_opts=["size=", "zipfile="],
                            extra_option_handler=option_handler)

    if (len(args) != 1):
        common.Usage(__doc__)
        sys.exit(1)

    intel_common.MakeVFATFilesystem(OPTIONS.zipfile, args[0], size=OPTIONS.size)
    common.Cleanup()

if __name__ == '__main__':
    try:
        common.CloseInheritedPipes()
        main(sys.argv[1:])
    except common.ExternalError, e:
        print
        print "   ERROR: %s" % (e,)
        print
        sys.exit(1)

