#!/bin/bash

set -e

if [ -z "$1" ]; then
    PACKAGE="$OUT/ota-dev.zip"
else
    PACKAGE="$1"
fi

if [ ! "$2" ]; then dutID=$(adb devices | grep -v 'List' | awk '{print ($1)}'); else dutID=$2; fi

function wait_for_adb {
    while [ -z "$(adb devices | grep $dutID | awk '{print($1)}')" ]; do
        sleep 1
    done
}

echo "Waiting for device : $dutID"
wait_for_adb
echo "Setting root permissions..."
adb -s $dutID root
sleep 1
wait_for_adb

echo "Copying OTA image $(basename $PACKAGE) to device..."
adb -s $dutID push $PACKAGE /data/local/tmp/update.zip
echo "Setting parameters and rebooting into recovery console..."
adb -s $dutID shell "mkdir -p /cache/recovery"
adb -s $dutID shell "echo \"--update_package=/data/local/tmp/update.zip\" > /cache/recovery/command"
adb -s $dutID shell start pre-recovery

