LOCAL_AOSP_PROJECT_LIST :=   \
			art  \
			bionic  \
			bootable/recovery  \
			build/blueprint  \
			build/kati  \
			build/make  \
			build/soong  \
			compatibility/cdd  \
			cts  \
			dalvik  \
			development  \
			device/asus/fugu  \
			device/asus/fugu-kernel  \
			device/common  \
			device/generic/arm64  \
			device/generic/armv7-a-neon  \
			device/generic/car  \
			device/generic/common  \
			device/generic/goldfish  \
			device/generic/goldfish-opengl  \
			device/generic/lionhead  \
			device/generic/mini-emulator-arm64  \
			device/generic/mini-emulator-armv7-a-neon  \
			device/generic/mini-emulator-mips  \
			device/generic/mini-emulator-mips64  \
			device/generic/mini-emulator-x86  \
			device/generic/mini-emulator-x86_64  \
			device/generic/mips  \
			device/generic/mips64  \
			device/generic/qemu  \
			device/generic/x86  \
			device/generic/x86_64  \
			device/google/accessory/arduino  \
			device/google/accessory/demokit  \
			device/google/atv  \
			device/google/contexthub  \
			device/google/dragon  \
			device/google/dragon-kernel  \
			device/google/vrservices  \
			device/huawei/angler  \
			device/huawei/angler-kernel  \
			device/lge/bullhead  \
			device/lge/bullhead-kernel  \
			device/linaro/hikey  \
			device/linaro/hikey-kernel  \
			device/sample  \
			docs/source.android.com  \
			external/ImageMagick  \
			external/Microsoft-GSL  \
			external/aac  \
			external/abi-compliance-checker  \
			external/abi-dumper  \
			external/adt-infra  \
			external/android-clat  \
			external/androidplot  \
			external/ant-glob  \
			external/antlr  \
			external/apache-commons-math  \
			external/apache-harmony  \
			external/apache-http  \
			external/apache-xml  \
			external/archive-patcher  \
			external/autotest  \
			external/avb  \
			external/bison  \
			external/blktrace  \
			external/boringssl  \
			external/bouncycastle  \
			external/bsdiff  \
			external/bzip2  \
			external/c-ares  \
			external/caliper  \
			external/cblas  \
			external/chromium-libpac  \
			external/chromium-trace  \
			external/chromium-webview  \
			external/clang  \
			external/cmockery  \
			external/compiler-rt  \
			external/conscrypt  \
			external/crcalc  \
			external/cros/system_api  \
			external/curl  \
			external/dagger2  \
			external/deqp  \
			external/desugar  \
			external/dexmaker  \
			external/dhcpcd-6.8.2  \
			external/dlmalloc  \
			external/dng_sdk  \
			external/dnsmasq  \
			external/doclava  \
			external/donuts  \
			external/drm_gralloc  \
			external/drm_hwcomposer  \
			external/droiddriver  \
			external/dtc  \
			external/e2fsprogs  \
			external/easymock  \
			external/eclipse-basebuilder  \
			external/eclipse-windowbuilder  \
			external/eigen  \
			external/elfutils  \
			external/emma  \
			external/esd  \
			external/expat  \
			external/eyes-free  \
			external/f2fs-tools  \
			external/fdlibm  \
			external/fec  \
			external/fio  \
			external/flac  \
			external/flatbuffers  \
			external/fmtlib  \
			external/fonttools  \
			external/freetype  \
			external/fsck_msdos  \
			external/gemmlowp  \
			external/giflib  \
			external/glide  \
			external/google-api-services-storage  \
			external/google-benchmark  \
			external/google-breakpad  \
			external/google-fonts/carrois-gothic-sc  \
			external/google-fonts/coming-soon  \
			external/google-fonts/cutive-mono  \
			external/google-fonts/dancing-script  \
			external/google-tv-pairing-protocol  \
			external/googletest  \
			external/gptfdisk  \
			external/guava  \
			external/guice  \
			external/hamcrest  \
			external/harfbuzz_ng  \
			external/hyphenation-patterns  \
			external/icu  \
			external/ims  \
			external/iproute2  \
			external/ipsec-tools  \
			external/iptables  \
			external/iputils  \
			external/iw  \
			external/jacoco  \
			external/jarjar  \
			external/javasqlite  \
			external/javassist  \
			external/jcommander  \
			external/jdiff  \
			external/jemalloc  \
			external/jline  \
			external/jmdns  \
			external/jsilver  \
			external/jsmn  \
			external/jsoncpp  \
			external/jsr305  \
			external/jsr330  \
			external/junit  \
			external/junit-params  \
			external/kernel-headers  \
			external/kmod  \
			external/ksoap2  \
			external/libavc  \
			external/libbrillo  \
			external/libcap  \
			external/libcap-ng  \
			external/libchrome  \
			external/libconstrainedcrypto  \
			external/libcups  \
			external/libcxx  \
			external/libcxxabi  \
			external/libdaemon  \
			external/libdivsufsort  \
			external/libdrm  \
			external/libedit  \
			external/libese  \
			external/libevent  \
			external/libexif  \
			external/libgdx  \
			external/libgsm  \
			external/libhevc  \
			external/libjpeg-turbo  \
			external/libldac  \
			external/liblzf  \
			external/libmicrohttpd  \
			external/libmojo  \
			external/libmpeg2  \
			external/libmtp  \
			external/libnetfilter_conntrack  \
			external/libnfnetlink  \
			external/libnl  \
			external/libogg  \
			external/libopus  \
			external/libpcap  \
			external/libphonenumber  \
			external/libpng  \
			external/libtextclassifier  \
			external/libunwind  \
			external/libunwind_llvm  \
			external/libusb  \
			external/libusb-compat  \
			external/libutf  \
			external/libvncserver  \
			external/libvorbis  \
			external/libvpx  \
			external/libvterm  \
			external/libweave  \
			external/libxml2  \
			external/libyuv  \
			external/linux-kselftest  \
			external/littlemock  \
			external/lld  \
			external/llvm  \
			external/ltp  \
			external/lz4  \
			external/lzma  \
			external/markdown  \
			external/mdnsresponder  \
			external/mesa3d  \
			external/messageformat  \
			external/minijail  \
			external/mksh  \
			external/mmc-utils  \
			external/mockftpserver  \
			external/mockito  \
			external/mockwebserver  \
			external/modp_b64  \
			external/mp4parser  \
			external/mtpd  \
			external/nanohttpd  \
			external/nanopb-c  \
			external/naver-fonts  \
			external/netcat  \
			external/netperf  \
			external/neven  \
			external/nfacct  \
			external/nist-pkits  \
			external/nist-sip  \
			external/noto-fonts  \
			external/oauth  \
			external/objenesis  \
			external/okhttp  \
			external/opencv  \
			external/openssh  \
			external/owasp/sanitizer  \
			external/parameter-framework  \
			external/pcre  \
			external/pdfium  \
			external/piex  \
			external/ppp  \
			external/proguard  \
			external/protobuf  \
			external/regex-re2  \
			external/replicaisland  \
			external/rmi4utils  \
			external/robolectric  \
			external/roboto-fonts  \
			external/rootdev  \
			external/safe-iop  \
			external/scrypt  \
			external/seccomp-tests  \
			external/selinux  \
			external/sfntly  \
			external/shflags  \
			external/skia  \
			external/sl4a  \
			external/slf4j  \
			external/smali  \
			external/snakeyaml  \
			external/sonic  \
			external/sonivox  \
			external/speex  \
			external/sqlite  \
			external/squashfs-tools  \
			external/strace  \
			external/stressapptest  \
			external/svox  \
			external/swiftshader  \
			external/syslinux  \
			external/tagsoup  \
			external/tcpdump  \
			external/testng  \
			external/timezonepicker-support  \
			external/tinyalsa  \
			external/tinycompress  \
			external/tinyxml  \
			external/tinyxml2  \
			external/toybox  \
			external/tpm2  \
			external/tremolo  \
			external/unicode  \
			external/v8  \
			external/valgrind  \
			external/vboot_reference  \
			external/vixl  \
			external/vogar  \
			external/volley  \
			external/vulkan-validation-layers  \
			external/webp  \
			external/webrtc  \
			external/wpa_supplicant_8  \
			external/wycheproof  \
			external/x264  \
			external/xmlrpcpp  \
			external/xmlwriter  \
			external/xmp_toolkit  \
			external/zlib  \
			external/zopfli  \
			external/zxing  \
			frameworks/av  \
			frameworks/base  \
			frameworks/compile/libbcc  \
			frameworks/compile/mclinker  \
			frameworks/compile/slang  \
			frameworks/data-binding  \
			frameworks/ex  \
			frameworks/hardware/interfaces  \
			frameworks/minikin  \
			frameworks/ml  \
			frameworks/multidex  \
			frameworks/native  \
			frameworks/opt/bitmap  \
			frameworks/opt/bluetooth  \
			frameworks/opt/calendar  \
			frameworks/opt/chips  \
			frameworks/opt/colorpicker  \
			frameworks/opt/datetimepicker  \
			frameworks/opt/emoji  \
			frameworks/opt/inputconnectioncommon  \
			frameworks/opt/inputmethodcommon  \
			frameworks/opt/net/ethernet  \
			frameworks/opt/net/ims  \
			frameworks/opt/net/voip  \
			frameworks/opt/net/wifi  \
			frameworks/opt/photoviewer  \
			frameworks/opt/setupwizard  \
			frameworks/opt/telephony  \
			frameworks/opt/timezonepicker  \
			frameworks/opt/vcard  \
			frameworks/rs  \
			frameworks/support  \
			frameworks/webview  \
			frameworks/wilhelm  \
			hardware/akm  \
			hardware/broadcom/libbt  \
			hardware/broadcom/wlan  \
			hardware/google/apf  \
			$(INTEL_PATH_HARDWARE)/audio_media  \
			$(INTEL_PATH_HARDWARE)/bootstub  \
			$(INTEL_PATH_HARDWARE)/common/bd_prov  \
			$(INTEL_PATH_HARDWARE)/common/libmix  \
			$(INTEL_PATH_HARDWARE)/common/libstagefrighthw  \
			$(INTEL_PATH_HARDWARE)/common/libva  \
			$(INTEL_PATH_HARDWARE)/common/libwsbm  \
			$(INTEL_PATH_HARDWARE)/common/omx-components  \
			$(INTEL_PATH_HARDWARE)/common/utils  \
			$(INTEL_PATH_HARDWARE)/common/wrs_omxil_core  \
			$(INTEL_PATH_HARDWARE)/img/hwcomposer  \
			$(INTEL_PATH_HARDWARE)/img/psb_headers  \
			$(INTEL_PATH_HARDWARE)/img/psb_video  \
			$(INTEL_PATH_HARDWARE)/sensors  \
			hardware/interfaces  \
			hardware/invensense  \
			hardware/libhardware  \
			hardware/libhardware_legacy  \
			hardware/marvell/bt  \
			hardware/qcom/audio  \
			hardware/qcom/bootctrl  \
			hardware/qcom/bt  \
			hardware/qcom/data/ipacfg-mgr  \
			hardware/qcom/display  \
			hardware/qcom/gps  \
			hardware/qcom/keymaster  \
			hardware/qcom/media  \
			hardware/qcom/msm8960  \
			hardware/qcom/msm8994  \
			hardware/qcom/msm8x26  \
			hardware/qcom/msm8x27  \
			hardware/qcom/msm8x84  \
			hardware/qcom/power  \
			hardware/qcom/wlan  \
			hardware/ril  \
			libcore  \
			libnativehelper  \
			packages/apps/BasicSmsReceiver  \
			packages/apps/Bluetooth  \
			packages/apps/Browser2  \
			packages/apps/Calendar  \
			packages/apps/Camera2  \
			packages/apps/Car/Dialer  \
			packages/apps/Car/Hvac  \
			packages/apps/Car/LatinIME  \
			packages/apps/Car/LensPicker  \
			packages/apps/Car/LocalMediaPlayer  \
			packages/apps/Car/Media  \
			packages/apps/Car/Messenger  \
			packages/apps/Car/Overview  \
			packages/apps/Car/Radio  \
			packages/apps/Car/Settings  \
			packages/apps/Car/Stream  \
			packages/apps/Car/SystemUpdater  \
			packages/apps/Car/UserManagement  \
			packages/apps/Car/libs  \
			packages/apps/CarrierConfig  \
			packages/apps/CellBroadcastReceiver  \
			packages/apps/CertInstaller  \
			packages/apps/Contacts  \
			packages/apps/DeskClock  \
			packages/apps/DevCamera  \
			packages/apps/Dialer  \
			packages/apps/Dialer2Prebuilt/v7  \
			packages/apps/DocumentsUI  \
			packages/apps/Email  \
			packages/apps/EmergencyInfo  \
			packages/apps/ExactCalculator  \
			packages/apps/Gallery  \
			packages/apps/Gallery2  \
			packages/apps/HTMLViewer  \
			packages/apps/KeyChain  \
			packages/apps/Launcher2  \
			packages/apps/Launcher3  \
			packages/apps/LegacyCamera  \
			packages/apps/ManagedProvisioning  \
			packages/apps/Messaging  \
			packages/apps/Music  \
			packages/apps/MusicFX  \
			packages/apps/Nfc  \
			packages/apps/OneTimeInitializer  \
			packages/apps/PackageInstaller  \
			packages/apps/Phone  \
			packages/apps/PhoneCommon  \
			packages/apps/Protips  \
			packages/apps/Provision  \
			packages/apps/QuickSearchBox  \
			packages/apps/RetailDemo  \
			packages/apps/SafetyRegulatoryInfo  \
			packages/apps/Settings  \
			packages/apps/SoundRecorder  \
			packages/apps/SpareParts  \
			packages/apps/SpeechRecorder  \
			packages/apps/Stk  \
			packages/apps/StorageManager  \
			packages/apps/Tag  \
			packages/apps/Terminal  \
			packages/apps/Test/connectivity  \
			packages/apps/TvSettings  \
			packages/apps/UnifiedEmail  \
			packages/apps/WallpaperPicker  \
			packages/inputmethods/LatinIME  \
			packages/inputmethods/OpenWnn  \
			packages/providers/ApplicationsProvider  \
			packages/providers/BlockedNumberProvider  \
			packages/providers/BookmarkProvider  \
			packages/providers/CalendarProvider  \
			packages/providers/CallLogProvider  \
			packages/providers/ContactsProvider  \
			packages/providers/DownloadProvider  \
			packages/providers/MediaProvider  \
			packages/providers/PartnerBookmarksProvider  \
			packages/providers/TelephonyProvider  \
			packages/providers/TvProvider  \
			packages/providers/UserDictionaryProvider  \
			packages/screensavers/Basic  \
			packages/screensavers/PhotoTable  \
			packages/screensavers/WebView  \
			packages/services/BuiltInPrintService  \
			packages/services/Car  \
			packages/services/Mms  \
			packages/services/NetworkRecommendation  \
			packages/services/Rcs  \
			packages/services/Telecomm  \
			packages/services/Telephony  \
			packages/wallpapers/LivePicker  \
			pdk  \
			platform_testing  \
			prebuilts/android-emulator  \
			prebuilts/build-tools  \
			prebuilts/checkcolor  \
			prebuilts/checkstyle  \
			prebuilts/clang/host/darwin-x86  \
			prebuilts/clang/host/linux-x86  \
			prebuilts/deqp  \
			prebuilts/devtools  \
			prebuilts/eclipse  \
			prebuilts/gcc/darwin-x86/aarch64/aarch64-linux-android-4.9  \
			prebuilts/gcc/darwin-x86/arm/arm-eabi-4.8  \
			prebuilts/gcc/darwin-x86/arm/arm-linux-androideabi-4.9  \
			prebuilts/gcc/darwin-x86/host/i686-apple-darwin-4.2.1  \
			prebuilts/gcc/darwin-x86/mips/mips64el-linux-android-4.9  \
			prebuilts/gcc/darwin-x86/x86/x86_64-linux-android-4.9  \
			prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9  \
			prebuilts/gcc/linux-x86/arm/arm-eabi-4.8  \
			prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9  \
			prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.11-4.8  \
			prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8  \
			prebuilts/gcc/linux-x86/host/x86_64-w64-mingw32-4.8  \
			prebuilts/gcc/linux-x86/mips/mips64el-linux-android-4.9  \
			prebuilts/gcc/linux-x86/x86/x86_64-linux-android-4.9  \
			prebuilts/go/darwin-x86  \
			prebuilts/go/linux-x86  \
			prebuilts/gradle-plugin  \
			prebuilts/libs/libedit  \
			prebuilts/maven_repo/android  \
			prebuilts/maven_repo/bumptech  \
			prebuilts/misc  \
			prebuilts/ndk  \
			prebuilts/python/darwin-x86/2.7.5  \
			prebuilts/python/linux-x86/2.7.5  \
			prebuilts/qemu-kernel  \
			prebuilts/sdk  \
			prebuilts/tools  \
			sdk  \
			system/bt  \
			system/ca-certificates  \
			system/chre  \
			system/connectivity/wificond  \
			system/connectivity/wifilogd  \
			system/core  \
			system/extras  \
			system/gatekeeper  \
			system/hardware/interfaces  \
			system/hwservicemanager  \
			system/keymaster  \
			system/libfmq  \
			system/libhidl  \
			system/libhwbinder  \
			system/libufdt  \
			system/libvintf  \
			system/media  \
			system/netd  \
			system/nfc  \
			system/security  \
			system/sepolicy  \
			system/tools/aidl  \
			system/tools/hidl  \
			system/update_engine  \
			system/vold  \
			test/vts  \
			test/vts-testcase/fuzz  \
			test/vts-testcase/hal  \
			test/vts-testcase/hal-trace  \
			test/vts-testcase/kernel  \
			test/vts-testcase/performance  \
			test/vts-testcase/vndk  \
			toolchain/binutils  \
			tools/acloud  \
			tools/apksig  \
			tools/libtf  \
			tools/loganalysis  \
			tools/repohooks  \
			tools/test/connectivity  \
			tools/tradefederation/contrib  \
			tools/tradefederation/core  \
			vendor/google_tradefederation/contrib  \
			vendor/google_tradefederation/core  \
			vendor/google_vts  \
