LOCAL_NO_DEFAULT_COMPILER_FLAGS := true
LOCAL_CC := $(IAFW_CC)
LOCAL_CFLAGS += $(TARGET_IAFW_GLOBAL_CFLAGS)
LOCAL_ASFLAGS += $(TARGET_IAFW_ASFLAGS)
LOCAL_CLANG := false

include $(BUILD_STATIC_LIBRARY)

