#! /bin/sh

# Start-up script for KeystoreSigner

KEYSTORESIGNER_HOME=`dirname "$0"`
KEYSTORESIGNER_HOME=`dirname "$KEYSTORESIGNER_HOME"`

java -Xmx512M -jar "$KEYSTORESIGNER_HOME"/framework/BootKeystoreSigner_ecss.jar -providerClass com.intel.ecss.jce.provider.IntelECSSProvider "$@"
